name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
          wait-on-timeout-error: 'Timed out waiting for localhost:3000'
          wait-on-retry-interval: 1000
          wait-on-silent-output: true
          cypress-command: npm run cypress:run
          cypress-cache-folder: ${{ runner.temp }}/.cache/Cypress
          cypress-run-args: --record --key ${{ secrets.CYPRESS_RECORD_KEY }}